sudo: required
services:
  - docker

before_install:
  - docker build -t joydeepmazumder/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run CI=true joydeepmazumder/react-test npm test

after_success:
  - docker build -t joydeepmazumder/multi-client ./client
  - docker build -t joydeepmazumder/multi-nginx ./nginx
  - docker build -t joydeepmazumder/multi-server ./server
  - docker build -t joydeepmazumder/multi-worker ./worker
  ## login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push joydeepmazumder/multi-client
  - docker push joydeepmazumder/multi-nginx
  - docker push joydeepmazumder/multi-server
  - docker push joydeepmazumder/multi-worker