sudo: required
services:
  - docker

before_install:
  - docker build -t joydeepmazumder/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true joydeepmazumder/react-test npm test

after_success:
  - docker build -t joydeepmazumder/multi-client ./client
  - docker build -t joydeepmazumder/multi-nginx ./nginx
  - docker build -t joydeepmazumder/multi-server ./server
  - docker build -t joydeepmazumder/multi-worker ./worker
  ## login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push joydeepmazumder/multi-client
  - docker push joydeepmazumder/multi-nginx
  - docker push joydeepmazumder/multi-server
  - docker push joydeepmazumder/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-ap-south-1-784241885377
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY